import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { asList, asMap, asText, parseWorkflow, type YamlMap, type YamlValue } from './workflow-yaml';
import { conditionHolds, interpolate, PLAIN_TAG, type Context } from './workflow-expressions';

// SHA256SUMS is the release's answer to "are these the bytes we published?".
// It is generated by one line in release.yml,
//
//     working-directory: dist
//     run: sha256sum vc-* version.json > SHA256SUMS
//
// and the operands are typed out. Measured on the v0.2.51 asset: seven lines,
// six CLI binaries and version.json. The release also publishes three things a
// person actually double-clicks --
//
//     void-code-mac-arm64.zip          207 MB
//     void-code-mac-x64.zip            214 MB
//     Void-Code-windows-x64.exe        149 MB
//
// -- and none of them is in the list. There is nothing to check them against,
// on any route, by anyone.
//
// This is the same fault as the Intel bundle that release-desktop-attach-
// workflow.test.ts next door is written about, one step further down the line:
// what a run produces is stated once, in the build workflows, and stated a
// second time by hand in release.yml, and the second copy does not learn.
// There it was the list of things to ATTACH. Here it is the list of things to
// HASH, and it has the same shape and the same failure mode -- a green run that
// publishes an unverifiable file.
//
// So the rule is not "add three names to the sha256sum line":
//
//   1. Every asset the release publishes, the list itself aside, has a line in
//      SHA256SUMS. Derived from what the run publishes, not from a list of
//      today's ten.
//   2. The names in it stay bare basenames. That is not cosmetic: install.sh
//      looks its download up with
//          awk -v n="$_ss_name" '$2 == n || $2 == "*" n { print $1; exit }'
//      over `${VC_ARTIFACT_PATH##*/}`, and install.ps1 does the same. A list
//      written as `dist/vc-darwin-arm64` satisfies rule 1 and verifies nothing
//      for anybody -- it is the pleasant-looking fix, so it is asked about.
//   3. Whatever writes the list writes it in a format that awk can read. The
//      tool is named rather than assumed for the same reason: `openssl dgst`
//      prints `SHA256(f)= h`, which is rule 2 broken in a different place.
//   4. Nothing is hashed that the run does not have. `sha256sum` on a path
//      nothing produced exits non-zero and takes the step with it, so a name
//      that outlives what it named does not go quietly -- it goes red on the
//      release, which is the worst place to find out.
//   5. And the one that makes the rest hold tomorrow: THE LIST LIVES IN ONE
//      PLACE, stated as a mutation. A third macOS architecture is added to
//      desktop-mac-app.yml's matrix, release.yml is left untouched byte for
//      byte, and rules 1 and 4 are asked again; then arm64 is removed and they
//      are asked again. An arrangement that enumerates fails both directions.
//      One that derives -- a glob over a staging directory -- passes both
//      without being told what the new row is called.
//
// A note on where the fix can live, because this file's model has an opinion
// and it is a deliberate one. Files are staged into a job only from jobs that
// job `needs`. The `release` job needs `build` and nothing desktop -- on
// purpose, so a desktop build dying on a runner cannot withhold the CLI release
// -- so no glob written inside `release` can reach a bundle: the artifacts are
// not there yet, and on a real run they may not exist at all. Widening `vc-*`
// to `*` therefore does not go green here, and must not: it would be a list
// that is complete or not depending on which runner finished first.
//
// What this file cannot do: it cannot push a tag, it cannot run GitHub Actions,
// and it cannot hash a byte. It fixes the FORM of the workflow -- which files a
// job holds when the checksum line runs, which of them that line names, and
// which names come out. That a real run produces a list matching the real bytes
// is unverified here, by anyone, and a green suite must not be read as saying
// so.
//
// One interaction, measured rather than guessed, because whoever implements
// this will meet it and should not have to find it twice. A candidate fix was
// applied to release.yml, run, and reverted: `gh release download --pattern
// SHA256SUMS` in the attaching job, `sha256sum * >> ../SHA256SUMS` over what it
// staged, `gh release upload SHA256SUMS --clobber`. Every rule here went green.
// release-desktop-attach-workflow.test.ts went RED, twice, both on its
// "attaches nothing it did not stage" rule: its model stages a job's files from
// `actions/download-artifact` alone, so a list the job fetched with `gh` looks
// to it like a path pointing at nothing. That is that file's model being
// narrower than the workflow, not a conflict between the two rules -- a job may
// hold a file it fetched or wrote, and both rules are true of the same run. The
// implementation is not finished while that one is red; teaching its stagedBy()
// about the file a job brings back is part of this change, not a separate one.
//
// Out of scope, and named so it is not mistaken for covered: `publish-auth`
// needs `release` alone, so the copy it syncs to $AUTH_HOST is the list as the
// `release` job left it. If the desktop names are added by a later job, that
// route serves the shorter list until someone changes what publish-auth waits
// for. This file asserts about the list the RELEASE carries, which is what the
// GitHub mirror path in install.sh reads.

// ---------------------------------------------------------------------------
// Reading a release run: what each job holds, and what it writes.
//
// workflow-yaml.ts is a reader, not a validator, and neither is anything below
// it, so none of it is trusted on the real files until it has been shown
// answering correctly -- and answering DIFFERENTLY -- on the synthetic
// workflows further down.
//
// The overlap with release-desktop-attach-workflow.test.ts is the glob matcher
// and the matrix reader, some thirty lines. That file asks which artifacts
// reach the release; this one asks what a job's working directory holds at the
// moment a command runs, step by step, which is a walk that file has no need
// of. Whoever next has cause to touch both can lift the shared half into a
// plain module the way workflow-yaml.ts was lifted.
// ---------------------------------------------------------------------------

type Read = (workflow: string) => string;

const LOCAL = './.github/workflows/';

const lines = (text: string) => text.split('\n').map((line) => line.trim()).filter((line) => line !== '');
const basename = (path: string) => path.split('/').filter((part) => part !== '').pop() ?? path;
// `..` is resolved rather than carried, because a step whose working-directory
// is one level down writes its output back up with one -- and `dist/../SUMS`
// and `SUMS` have to be the same file here or the walk loses track of it.
const normalize = (path: string) => {
  const parts: string[] = [];
  for (const part of path.replace(/\/{2,}/g, '/').split('/')) {
    if (part === '' || part === '.') continue;
    if (part === '..' && parts.length > 0 && parts[parts.length - 1] !== '..') parts.pop();
    else parts.push(part);
  }
  return parts.join('/') || '.';
};

// A glob as GitHub and the shell mean it: `*` stands for a run of characters
// within one path segment and never crosses a `/`.
const escapeRegExp = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const asRegExp = (pattern: string) => new RegExp(`^${pattern.split('*').map(escapeRegExp).join('[^/]*')}$`);
const covers = (pattern: string, candidate: string) => asRegExp(normalize(pattern)).test(normalize(candidate).replace(/\*/g, 'x'));
const isGlob = (pattern: string) => pattern.includes('*') || pattern.includes('?') || pattern.includes('[');

const stepsOf = (job: YamlMap) => asList(job.steps).map(asMap);
const transcriptOf = (job: YamlMap) => stepsOf(job).map((step) => `${asText(step.uses)}\n${asText(step.run)}`).join('\n \n');

// Does this job package the desktop app? Answered from what it runs, so a
// renamed job or a third reusable workflow is still recognised.
const PACKAGES_DESKTOP = /\bpackage:mac\b|\bpackage:win\b|(?:^|[\s/])electron-builder\s/;

const RELEASE_ACTION = /softprops\/action-gh-release|ncipollo\/release-action|actions\/create-release/;

// The tools whose output install.sh's awk can read: `<hash>  <name>`, hash
// first, name second. Named rather than inferred -- see rule 3.
const SUM_TOOLS = new Set(['sha256sum', 'gsha256sum', 'shasum', 'sha256']);

// Flags that swallow the word after them, so `shasum -a 256 f` does not report
// `256` as a file nothing produced.
const FLAGS_TAKING_A_VALUE = new Set(['-a', '--algorithm', '-b', '--binary-flag']);

const SUMS_FILE = 'SHA256SUMS';

function matrixRows(job: YamlMap, where: string): YamlMap[] {
  const matrix = asMap(asMap(job.strategy).matrix);
  const included = asList(matrix.include).map(asMap);
  const axes = Object.entries(matrix).filter(([key]) => key !== 'include' && key !== 'exclude');
  if (axes.length > 1) throw new Error(`${where} has a matrix of ${axes.length} axes, which this test does not model`);
  const spread = axes.length === 1 ? asList(axes[0][1]).map((value) => ({ [axes[0][0]]: asText(value) })) : [];
  const rows = [...spread, ...included];
  return rows.length > 0 ? rows : [{}];
}

const substitute = (text: string, row: YamlMap) =>
  text.replace(/\$\{\{\s*matrix\.([A-Za-z0-9_-]+)\s*\}\}/g, (whole, key: string) => {
    const value = row[key];
    return typeof value === 'string' ? value : whole;
  });

const jobsOf = (read: Read, workflow: string): [string, YamlMap][] =>
  Object.entries(asMap(parseWorkflow(read(workflow)).jobs)).map(([name, value]) => [name, asMap(value)]);

// `via` is the release.yml job the artifact arrives through -- the job itself,
// or the job whose `uses:` called the reusable workflow that uploaded it. It is
// what makes `needs` answerable: an artifact is available to a job only if the
// job it came through is one this job waited for.
type Artifact = {
  readonly via: string;
  readonly name: string;
  readonly files: readonly string[];
  readonly desktop: boolean;
};

function uploadsIn(read: Read, workflow: string, via: string, context: Context): Artifact[] {
  const artifacts: Artifact[] = [];
  for (const [jobName, job] of jobsOf(read, workflow)) {
    const desktop = PACKAGES_DESKTOP.test(transcriptOf(job));
    for (const row of matrixRows(job, `${workflow}:${jobName}`)) {
      for (const step of stepsOf(job)) {
        if (!/actions\/upload-artifact/.test(asText(step.uses))) continue;
        const settings = asMap(step.with);
        const resolve = (value: YamlValue | undefined) => interpolate(substitute(asText(value), row), context);
        artifacts.push({ via, name: resolve(settings.name), files: lines(resolve(settings.path)).map(basename), desktop });
      }
    }
  }
  return artifacts;
}

// uploadsIn() walks a whole workflow, which is what a `uses:` call means: one
// release.yml job stands for every job in the file it calls. A job that uploads
// on its own behalf is a different question -- only its own steps count -- so it
// is asked separately rather than by filtering the other answer.
function ownUploads(read: Read, jobName: string, job: YamlMap, context: Context): Artifact[] {
  const desktop = PACKAGES_DESKTOP.test(transcriptOf(job));
  const artifacts: Artifact[] = [];
  for (const row of matrixRows(job, `release.yml:${jobName}`)) {
    for (const step of stepsOf(job)) {
      if (!/actions\/upload-artifact/.test(asText(step.uses))) continue;
      const settings = asMap(step.with);
      const resolve = (value: YamlValue | undefined) => interpolate(substitute(asText(value), row), context);
      artifacts.push({ via: jobName, name: resolve(settings.name), files: lines(resolve(settings.path)).map(basename), desktop });
    }
  }
  return artifacts;
}

function artifactsOfRun(read: Read, context: Context): Artifact[] {
  const produced: Artifact[] = [];
  for (const [name, job] of jobsOf(read, 'release.yml')) {
    if (!conditionHolds(asText(job.if), context)) continue;
    const called = asText(job.uses);
    if (called.startsWith(LOCAL)) produced.push(...uploadsIn(read, called.slice(LOCAL.length).split('@')[0], name, context));
    else produced.push(...ownUploads(read, name, job, context));
  }
  return produced;
}

// The order jobs run in, and what each waited for. A cycle raises rather than
// being read as "no dependencies".
function dependencyOrder(jobs: Map<string, YamlMap>): string[] {
  const done = new Set<string>();
  const ordered: string[] = [];
  const visit = (name: string, stack: readonly string[]) => {
    if (done.has(name)) return;
    if (stack.includes(name)) throw new Error(`release.yml has a cycle in needs: ${[...stack, name].join(' -> ')}`);
    for (const need of asList(jobs.get(name)?.needs).map(asText)) {
      if (jobs.has(need)) visit(need, [...stack, name]);
    }
    done.add(name);
    ordered.push(name);
  };
  for (const name of jobs.keys()) visit(name, []);
  return ordered;
}

function waitedFor(jobs: Map<string, YamlMap>, name: string): Set<string> {
  const reached = new Set<string>();
  const walk = (current: string) => {
    for (const need of asList(jobs.get(current)?.needs).map(asText)) {
      if (!jobs.has(need) || reached.has(need)) continue;
      reached.add(need);
      walk(need);
    }
  };
  walk(name);
  return reached;
}

// ---------------------------------------------------------------------------
// The shell, to the depth these workflows use it: where a file comes from and
// where a command's output goes.
// ---------------------------------------------------------------------------

// Heredoc bodies are content, not commands: `cat > version.json <<EOF` is
// followed by JSON, and reading it as shell finds redirections that are not
// there. Line continuations are joined first so a command split over two lines
// is still one command.
function commandsIn(script: string): string[] {
  const source = script.replace(/\\\n/g, ' ').split('\n');
  const commands: string[] = [];
  for (let index = 0; index < source.length; index += 1) {
    const line = source[index];
    const heredoc = /<<-?\s*'?"?([A-Za-z_][A-Za-z0-9_]*)'?"?/.exec(line);
    commands.push(...line.split(/&&|\|\||;/).map((part) => part.trim()).filter((part) => part !== '' && !part.startsWith('#')));
    if (!heredoc) continue;
    index += 1;
    while (index < source.length && source[index].trim() !== heredoc[1]) index += 1;
  }
  return commands;
}

// Redirection operators are spaced out first so `>SHA256SUMS` and
// `> SHA256SUMS` tokenize the same. `2>&1` becomes `2 > &1`, whose target is
// not a checksum list and is ignored below.
function words(command: string): string[] {
  const spaced = command.replace(/>>?/g, (operator) => ` ${operator} `);
  return Array.from(spaced.matchAll(/'[^']*'|"[^"]*"|\S+/g), (found) => found[0].replace(/^['"]|['"]$/g, ''));
}

type Redirection = { readonly target: string; readonly append: boolean; readonly before: readonly string[] };

function redirection(command: string): Redirection | null {
  const token = words(command);
  const at = token.findIndex((word) => word === '>' || word === '>>');
  if (at < 0 || at + 1 >= token.length) return null;
  return { target: token[at + 1], append: token[at] === '>>', before: token.slice(0, at) };
}

const join = (directory: string, path: string) =>
  normalize(path.startsWith('/') ? path : directory === '' || directory === '.' ? path : `${directory}/${path}`);

// ---------------------------------------------------------------------------
// The walk.
// ---------------------------------------------------------------------------

type Report = {
  readonly trouble: string;
  // Basenames of everything the run attaches to the release.
  readonly published: readonly string[];
  readonly desktopPublished: readonly string[];
  // Names as they are written into the list, which is what an installer looks
  // its download up by.
  readonly listed: readonly string[];
  readonly unlisted: readonly string[];
  readonly desktopUnlisted: readonly string[];
  readonly notBasenames: readonly string[];
  readonly phantom: readonly string[];
  readonly unreadableWriter: readonly string[];
  readonly writers: readonly string[];
};

const EMPTY: Report = {
  trouble: '', published: [], desktopPublished: [], listed: [], unlisted: [],
  desktopUnlisted: [], notBasenames: [], phantom: [], unreadableWriter: [], writers: [],
};

function walk(read: Read, context: Context): Report {
  const jobs = new Map(jobsOf(read, 'release.yml'));
  const produced = artifactsOfRun(read, context);

  // Basename -> the file the run holds it as, for everything already on the
  // release when a later job asks for it back.
  const published = new Map<string, boolean>();
  const listed = new Map<string, string>();
  const phantom: string[] = [];
  const unreadableWriter: string[] = [];
  const writers: string[] = [];
  const desktopFiles = new Set(produced.filter((artifact) => artifact.desktop).flatMap((artifact) => artifact.files));

  for (const jobName of dependencyOrder(jobs)) {
    const job = jobs.get(jobName) as YamlMap;
    if (!conditionHolds(asText(job.if), context)) continue;
    const available = produced.filter((artifact) => waitedFor(jobs, jobName).has(artifact.via));
    const jobDirectory = normalize(asText(asMap(asMap(job.defaults).run)['working-directory']) || '.');
    // What this job's workspace holds, as paths from the workspace root.
    const present = new Set<string>();

    for (const step of stepsOf(job)) {
      if (!conditionHolds(asText(step.if), context)) continue;
      const settings = asMap(step.with);
      const resolve = (value: YamlValue | undefined) => interpolate(asText(value), context);
      const uses = asText(step.uses);
      const directory = normalize(resolve(step['working-directory']) || jobDirectory);

      if (/actions\/download-artifact/.test(uses)) {
        const into = normalize(resolve(settings.path) || '.');
        const name = resolve(settings.name);
        const pattern = resolve(settings.pattern);
        const merged = resolve(settings['merge-multiple']) === 'true';
        for (const artifact of available) {
          const selected = name !== '' ? artifact.name === name : pattern !== '' ? covers(pattern, artifact.name) : true;
          if (!selected) continue;
          const at = name !== '' || merged ? into : `${into}/${artifact.name}`;
          for (const file of artifact.files) present.add(join(at, file));
        }
      }

      const script = resolve(step.run);
      for (const command of commandsIn(script)) {
        const token = words(command);
        // `gh release download` brings assets the release already carries back
        // onto the runner -- how a later job amends a list an earlier one wrote.
        if (/^gh$/.test(token[0] ?? '') && token[1] === 'release' && token[2] === 'download') {
          const flag = (...names: string[]) => {
            const at = token.findIndex((word) => names.includes(word));
            return at >= 0 ? token[at + 1] ?? '' : '';
          };
          const into = normalize(flag('--dir', '-D') || '.');
          const pattern = flag('--pattern', '-p');
          for (const asset of published.keys()) {
            if (pattern === '' || covers(pattern, asset)) present.add(join(into, asset));
          }
        }

        const redirect = redirection(command);
        if (!redirect) continue;
        const target = join(directory, redirect.target);
        if (basename(target) !== SUMS_FILE) {
          present.add(target);
          continue;
        }

        writers.push(`${jobName}: ${command}`);
        const tool = basename(redirect.before[0] ?? '');
        if (!SUM_TOOLS.has(tool)) {
          unreadableWriter.push(
            `${jobName} writes ${SUMS_FILE} with «${tool || command}», whose output install.sh's awk cannot read`,
          );
          present.add(target);
          continue;
        }
        if (!redirect.append) listed.clear();

        const prefix = directory === '.' || directory === '' ? '' : `${directory}/`;
        const operands = redirect.before.slice(1).filter((word, index, all) =>
          !word.startsWith('-') && !FLAGS_TAKING_A_VALUE.has(all[index - 1] ?? ''));
        for (const operand of operands) {
          let matched = 0;
          for (const file of present) {
            if (!file.startsWith(prefix)) continue;
            const relative = file.slice(prefix.length);
            if (!covers(operand, relative)) continue;
            matched += 1;
            listed.set(relative, jobName);
          }
          if (matched === 0) {
            phantom.push(
              `${jobName} hashes ${isGlob(operand) ? 'the pattern ' : ''}${operand}, which nothing in this run stages`,
            );
          }
        }
        present.add(target);
      }

      // What reaches the release: the action that creates it, and `gh release
      // upload` from any job that adds to it afterwards.
      const attaching: string[] = [];
      if (RELEASE_ACTION.test(uses)) attaching.push(...lines(resolve(settings.files)));
      for (const call of script.matchAll(/\bgh\s+release\s+(?:upload|create)\s+\S+([^\n]*)/g)) {
        attaching.push(...call[1].split(/\s+/).filter((word) => word !== '' && !word.startsWith('-')));
      }
      for (const path of attaching) {
        for (const file of present) {
          if (covers(join(directory, path), file)) published.set(basename(file), true);
        }
      }
    }
  }

  const owed = [...published.keys()].filter((asset) => asset !== SUMS_FILE);
  const named = new Set([...listed.keys()].map(basename));
  return {
    ...EMPTY,
    published: [...published.keys()].sort(),
    desktopPublished: owed.filter((asset) => desktopFiles.has(asset)).sort(),
    listed: [...listed.keys()].sort(),
    unlisted: owed.filter((asset) => !named.has(asset)).sort(),
    desktopUnlisted: owed.filter((asset) => desktopFiles.has(asset) && !named.has(asset)).sort(),
    notBasenames: [...listed.keys()].filter((name) => name.includes('/')).sort(),
    phantom: phantom.sort(),
    unreadableWriter: unreadableWriter.sort(),
    writers,
  };
}

function report(read: Read, context: Context): Report {
  try {
    return walk(read, context);
  } catch (error) {
    // Never the pleasant answer. A run this cannot read is reported as unread,
    // because "nothing is missing from the list" and "no list was looked at"
    // are otherwise the same green.
    return { ...EMPTY, trouble: `the release run could not be read: ${(error as Error).message}` };
  }
}

// ---------------------------------------------------------------------------
// The mutation: a third architecture, and a removed one. Textual, on the build
// workflow only, so what is asked is exactly what a real edit would ask --
// release.yml is not touched, and the question is whether it needed to be.
// ---------------------------------------------------------------------------

function editMatrixRow(text: string, value: string, replacement: string | null): string {
  const all = text.replace(/\r\n/g, '\n').split('\n');
  const start = all.findIndex((line) => new RegExp(`^\\s*-\\s+[A-Za-z0-9_-]+:\\s*${escapeRegExp(value)}\\s*$`).test(line));
  if (start < 0) throw new Error(`no matrix row in this workflow has a value of exactly ${value}`);
  const dent = all[start].length - all[start].trimStart().length;
  let end = start + 1;
  while (end < all.length && (all[end].trim() === '' || all[end].length - all[end].trimStart().length > dent)) end += 1;
  const row = all.slice(start, end);
  if (replacement === null) return [...all.slice(0, start), ...all.slice(end)].join('\n');
  const copy = row.map((line) => line.replace(new RegExp(`\\b${escapeRegExp(value)}\\b`, 'g'), replacement));
  return [...all.slice(0, end), ...copy, ...all.slice(end)].join('\n');
}

const withEditedRow = (read: Read, workflow: string, value: string, replacement: string | null): Read =>
  (name) => (name === workflow ? editMatrixRow(read(workflow), value, replacement) : read(name));

// ---------------------------------------------------------------------------
// The machinery, shown answering on workflows written for the purpose.
//
// Six release.yml bodies over one mac build workflow: the arrangement release.yml
// has today, the two ways of widening it that do not work, the derivation that
// does, and two ways of getting the derivation subtly wrong. Every rule below is
// asked of them, so a rule that cannot fail is visible here rather than in a
// release.
// ---------------------------------------------------------------------------

const HEAD = `
name: Fixture
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - artifact: cli-linux
    steps:
      - name: Build
        run: go build -o \${{ matrix.artifact }} ./cmd/vc
      - uses: actions/upload-artifact@abc123
        with:
          name: \${{ matrix.artifact }}
          path: \${{ matrix.artifact }}

  desktop-mac-app:
    if: \${{ vars.DESKTOP == 'true' }}
    uses: ./.github/workflows/mac.yml
`;

// The `release` job, with its checksum line left as a parameter. It waits for
// `build` and for nothing desktop, exactly as the real one does.
const releaseJob = (sums: string) => `
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@abc123
        with:
          path: dist
          merge-multiple: true
      - name: Generate version.json
        run: |
          cat > dist/version.json <<EOF
          { "tag": "\${{ github.ref_name }}" }
          EOF
${sums}
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/cli-linux
            dist/version.json
            dist/SHA256SUMS
`;

const ENUMERATED_SUMS = `      - name: Generate checksums
        working-directory: dist
        run: sha256sum cli-* version.json > SHA256SUMS`;

// The widening that looks like the fix and is not: `*` in a job that never
// waited for the desktop builds still cannot see them.
const WIDENED_SUMS = `      - name: Generate checksums
        working-directory: dist
        run: sha256sum * > SHA256SUMS`;

// The attaching job, in the two shapes it can have: one that enumerates what it
// hashes, one that derives it.
const ATTACH_HEAD = `
  attach:
    needs: [release, desktop-mac-app]
    if: \${{ vars.DESKTOP == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@abc123
        with:
          pattern: app-*
          merge-multiple: true
          path: desktop-installers
`;

const ATTACH_TAIL = `      - name: Attach
        run: gh release upload \${{ github.ref_name }} desktop-installers/* --clobber
`;

const AMENDS = `      - name: Bring the list back
        run: gh release download \${{ github.ref_name }} --pattern SHA256SUMS --dir .
      - name: Hash what this job staged
        working-directory: desktop-installers
        run: sha256sum * >> ../SHA256SUMS
      - name: Put the list back
        run: gh release upload \${{ github.ref_name }} SHA256SUMS --clobber
`;

// The same amendment with `>` for `>>`: the desktop names arrive and the CLI
// names go away.
const TRUNCATES = AMENDS.replace('sha256sum * >> ../SHA256SUMS', 'sha256sum * > ../SHA256SUMS');

// The same amendment run from the workspace root, so every name in the list
// carries the directory it was hashed in and no installer can find its own.
const PREFIXES = `      - name: Bring the list back
        run: gh release download \${{ github.ref_name }} --pattern SHA256SUMS --dir .
      - name: Hash what this job staged
        run: sha256sum desktop-installers/* >> SHA256SUMS
      - name: Put the list back
        run: gh release upload \${{ github.ref_name }} SHA256SUMS --clobber
`;

// And the same again written with a tool whose output is a different shape.
const WRONG_TOOL = AMENDS.replace('sha256sum * >> ../SHA256SUMS', 'openssl dgst -sha256 * >> ../SHA256SUMS');

const MAC = `
name: Mac
on:
  workflow_call:

jobs:
  package:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
          - arch: x64
    steps:
      - name: Package
        run: npm run package:mac
      - uses: actions/upload-artifact@abc123
        with:
          name: app-mac-\${{ matrix.arch }}
          path: desktop/release/app-mac-\${{ matrix.arch }}.zip
`;

const world = (sums: string, amendment: string): Read => (name) => {
  if (name === 'release.yml') return HEAD + releaseJob(sums) + ATTACH_HEAD + amendment + ATTACH_TAIL;
  if (name === 'mac.yml') return MAC;
  throw new Error(`the fixture has no workflow called ${name}`);
};

const TODAY = world(ENUMERATED_SUMS, '');
const WIDENED = world(WIDENED_SUMS, '');
const DERIVED = world(ENUMERATED_SUMS, AMENDS);
const TRUNCATING = world(ENUMERATED_SUMS, TRUNCATES);
const PREFIXING = world(ENUMERATED_SUMS, PREFIXES);
const OTHER_TOOL = world(ENUMERATED_SUMS, WRONG_TOOL);

const FIXTURE_ON: Context = { ...PLAIN_TAG, 'vars.DESKTOP': 'true' };

describe('the walk, on workflows written to exercise it', () => {
  it('sees what a release run publishes, through a reusable workflow and a matrix', () => {
    const found = report(TODAY, FIXTURE_ON);
    expect(found.trouble).toBe('');
    expect(found.published).toEqual(['SHA256SUMS', 'app-mac-arm64.zip', 'app-mac-x64.zip', 'cli-linux', 'version.json']);
    expect(found.desktopPublished).toEqual(['app-mac-arm64.zip', 'app-mac-x64.zip']);
  });

  it('reads the enumerated list as covering the CLI and nothing else', () => {
    const found = report(TODAY, FIXTURE_ON);
    expect(found.listed).toEqual(['cli-linux', 'version.json']);
    expect(found.unlisted).toEqual(['app-mac-arm64.zip', 'app-mac-x64.zip']);
    expect(found.phantom).toEqual([]);
  });

  it('does not let a widened glob in the release job stand in for waiting on the builds', () => {
    // `sha256sum *` in a job that needs `build` alone hashes what `build`
    // made. On a real run the desktop artifacts may not exist yet, and which
    // ones do depends on which runner finished first.
    const found = report(WIDENED, FIXTURE_ON);
    expect(found.listed).toEqual(['cli-linux', 'version.json']);
    expect(found.unlisted).toEqual(['app-mac-arm64.zip', 'app-mac-x64.zip']);
  });

  it('is satisfied by a job that waits for the builds and globs over what it staged', () => {
    const found = report(DERIVED, FIXTURE_ON);
    expect(found.trouble || found.unlisted.join(' | ')).toBe('');
    expect(found.listed).toEqual(['app-mac-arm64.zip', 'app-mac-x64.zip', 'cli-linux', 'version.json']);
    expect(found.notBasenames).toEqual([]);
    expect(found.phantom).toEqual([]);
    expect(found.unreadableWriter).toEqual([]);
  });

  it('separates "the desktop names arrived" from "the CLI names survived"', () => {
    const found = report(TRUNCATING, FIXTURE_ON);
    expect(found.desktopUnlisted).toEqual([]);
    expect(found.unlisted).toEqual(['cli-linux', 'version.json']);
  });

  it('catches a list whose names carry a directory, which no installer looks up', () => {
    const found = report(PREFIXING, FIXTURE_ON);
    expect(found.notBasenames).toEqual(['desktop-installers/app-mac-arm64.zip', 'desktop-installers/app-mac-x64.zip']);
  });

  it('catches a writer whose output is not the shape install.sh parses', () => {
    const found = report(OTHER_TOOL, FIXTURE_ON);
    expect(found.unreadableWriter.join(' | ')).toContain('openssl');
    expect(found.desktopUnlisted).toEqual(['app-mac-arm64.zip', 'app-mac-x64.zip']);
  });

  it('builds nothing desktop, and owes nothing desktop, when the switch is off', () => {
    const off = report(TODAY, PLAIN_TAG);
    expect(off.desktopPublished).toEqual([]);
    expect(off.unlisted).toEqual([]);
    expect(off.listed).toEqual(['cli-linux', 'version.json']);
  });

  it('reports a run it could not read instead of finding nothing wrong', () => {
    const twoAxes: Read = (name) => (name === 'mac.yml'
      ? MAC.replace(/matrix:\n(\s+)include:[^]*$/, 'matrix:\n$1arch: [arm64, x64]\n$1node: [20, 22]\n')
      : DERIVED(name));
    expect(report(twoAxes, FIXTURE_ON).trouble).toContain('does not model');
  });
});

describe('the mutation, on the same fixtures', () => {
  const third = (read: Read) => withEditedRow(read, 'mac.yml', 'arm64', 'universal');
  const without = (read: Read) => withEditedRow(read, 'mac.yml', 'arm64', null);

  it('really does add a build, and really does remove one', () => {
    expect(report(third(DERIVED), FIXTURE_ON).published).toContain('app-mac-universal.zip');
    expect(report(without(DERIVED), FIXTURE_ON).published).not.toContain('app-mac-arm64.zip');
  });

  it('leaves the derived arrangement clean in both directions', () => {
    for (const mutant of [third(DERIVED), without(DERIVED)]) {
      const found = report(mutant, FIXTURE_ON);
      expect(found.trouble || [...found.unlisted, ...found.notBasenames, ...found.phantom].join(' | ')).toBe('');
    }
  });

  it('fails an arrangement that enumerates, in both directions', () => {
    expect(report(third(TODAY), FIXTURE_ON).unlisted).toContain('app-mac-universal.zip');
    const enumeratedNames = world(`      - name: Generate checksums
        working-directory: dist
        run: sha256sum cli-linux version.json > SHA256SUMS`, `      - name: Hash what this job staged
        working-directory: desktop-installers
        run: sha256sum app-mac-arm64.zip app-mac-x64.zip >> SHA256SUMS
      - name: Put the list back
        run: gh release upload \${{ github.ref_name }} desktop-installers/SHA256SUMS --clobber
`);
    expect(report(without(enumeratedNames), FIXTURE_ON).phantom.join(' | '))
      .toContain('app-mac-arm64.zip, which nothing in this run stages');
  });
});

// ---------------------------------------------------------------------------
// The real workflows.
// ---------------------------------------------------------------------------

const readReal: Read = (name) => readFileSync(new URL(`../../.github/workflows/${name}`, import.meta.url), 'utf8');

// Whatever release.yml's own gate is spelled, this is the run where it is open.
// Derived from the file rather than named here, so the choice of switch stays
// where release-desktop-optin-workflow.test.ts left it: the implementer's.
const DESKTOP_ON: Context = {
  ...PLAIN_TAG,
  ...Object.fromEntries(Array.from(
    new Set(Array.from(readReal('release.yml').matchAll(/\bvars\.([A-Za-z_][A-Za-z_0-9]*)/g), (found) => found[1])),
    (name) => [`vars.${name}`, 'true'],
  )),
};

const enabled = report(readReal, DESKTOP_ON);
const plain = report(readReal, PLAIN_TAG);

const nothingPublished = 'the release run publishes nothing this test could read';
const verdict = (found: Report, answer: string) =>
  found.trouble !== '' ? found.trouble : found.published.length === 0 ? nothingPublished : answer;

describe('the checksum list covers every asset the release publishes', () => {
  it('has a release run to read at all, with the desktop bundles in it', () => {
    // Every rule under this one reads a list, and a list that came out empty
    // would satisfy all of them at once. This is that list, named out loud.
    expect(enabled.trouble || enabled.published.join(', ') || nothingPublished).toContain('SHA256SUMS');
    expect(enabled.desktopPublished.length).toBeGreaterThanOrEqual(3);
  });

  it('names the desktop bundles people download and double-click', () => {
    // Today: three bundles, 570 MB of them, and nothing on any route to check
    // them against. `sha256sum vc-* version.json` was written when the release
    // had no desktop half, and it has not learned that it has one.
    expect(verdict(enabled, enabled.desktopUnlisted.join(' | ') || 'every desktop bundle is in the list'))
      .toBe('every desktop bundle is in the list');
  });

  it('names everything else it publishes too, the list itself aside', () => {
    expect(verdict(enabled, enabled.unlisted.join(' | ') || 'every published asset is in the list'))
      .toBe('every published asset is in the list');
  });

  it('writes bare basenames, which is what install.sh and install.ps1 look up', () => {
    expect(verdict(enabled, enabled.notBasenames.join(' | ') || 'every name in the list is a basename'))
      .toBe('every name in the list is a basename');
  });

  it('is written by a tool whose output those two can parse', () => {
    expect(verdict(enabled, enabled.unreadableWriter.join(' | ') || 'the list is written as <hash>  <name>'))
      .toBe('the list is written as <hash>  <name>');
  });

  it('hashes nothing the run does not have, which would take the release step with it', () => {
    expect(verdict(enabled, enabled.phantom.join(' | ') || 'hashes what the run staged'))
      .toBe('hashes what the run staged');
  });
});

describe('a third architecture tomorrow needs no edit to release.yml', () => {
  // The whole point. release.yml is read unchanged; only the build workflow is
  // mutated, exactly as a real edit would.
  const macWorkflow = 'desktop-mac-app.yml';
  const third = report(withEditedRow(readReal, macWorkflow, 'arm64', 'universal'), DESKTOP_ON);
  const without = report(withEditedRow(readReal, macWorkflow, 'arm64', null), DESKTOP_ON);

  it('the mutation lands: one more bundle, named by the matrix and not by this test', () => {
    const added = third.published.filter((asset) => !enabled.published.includes(asset));
    expect(third.trouble || added.join(', ')).toMatch(/universal/);
  });

  it('and the new bundle is in the list anyway', () => {
    expect(verdict(third, third.desktopUnlisted.join(' | ') || 'every desktop bundle is in the list'))
      .toBe('every desktop bundle is in the list');
  });

  it('and a bundle that goes away leaves no name pointing at a file nobody builds', () => {
    // The other direction of the same fault. A name written twice is a name
    // that can outlive what it named, and `sha256sum` on a missing path exits
    // non-zero and fails the step -- on the release, where it is worst.
    expect(without.trouble || without.phantom.join(' | ') || 'nothing points at a build that is gone')
      .toBe('nothing points at a build that is gone');
  });
});

describe('and an ordinary tag still publishes a list of exactly what it built', () => {
  it('owes nothing desktop, because it built nothing desktop', () => {
    expect(plain.trouble || plain.desktopPublished.join(', ') || 'nothing desktop is published')
      .toBe('nothing desktop is published');
  });

  it('and still covers the CLI assets it does publish', () => {
    expect(verdict(plain, plain.unlisted.join(' | ') || 'every published asset is in the list'))
      .toBe('every published asset is in the list');
  });
});
