import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

describe('packaged renderer entry', () => {
  it('uses the production module bundler and official terminal construction path', () => {
    const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8')) as { scripts: Record<string, string> };
    const html = readFileSync(new URL('../src/renderer/index.html', import.meta.url), 'utf8');
    const css = readFileSync(new URL('../src/renderer/index.css', import.meta.url), 'utf8');
    const stack = readFileSync(new URL('../src/renderer/terminal-stack.ts', import.meta.url), 'utf8');
    const renderer = readFileSync(new URL('../src/renderer/index.ts', import.meta.url), 'utf8');
    const probe = readFileSync(new URL('../scripts/production-terminal-check.mjs', import.meta.url), 'utf8');
    expect(packageJson.scripts['bundle:renderer']).toContain('esbuild src/renderer/index.ts --bundle --format=esm');
    expect(html).toContain('<script type="module" src="index.js"></script>');
    expect(html).not.toContain('xterm.js');
    expect(html).toContain('id="recent-toggle" type="button" aria-controls="recent" aria-expanded="false"');
    expect(html).toContain('id="recent-close" type="button" data-l10n-aria="Close Recent Chats" aria-label=""');
    expect(css).toContain('clamp(240px,26vw,320px)');
    expect(css).toContain('@media(max-width:760px)');
    expect(stack).toContain("from '@xterm/xterm'");
    expect(stack).toContain("import '@xterm/xterm/css/xterm.css'");
    expect(renderer).not.toContain('data.match(');
    expect(renderer).not.toContain('\\x1b\\[');
    expect(probe).toContain("runProbe('missing-font', 'missing-font')");
    expect(probe).toContain("runProbe('palette-collapse', 'palette-collapse')");
    expect(renderer).toContain("{ name: 'tall', width: 1100, height: 1000 }");
    expect(renderer).toContain("{ name: 'short', width: 1100, height: 560 }");
    expect(renderer).toContain("{ name: 'narrow', width: 640, height: 760 }");
    expect(renderer).toContain('for (const rowCount of [1, 8])');
    expect(renderer).toContain('closedZeroWidth: closedPanelWidth === 0');
    expect(renderer).toContain("getComputedStyle(recentElement).position === 'fixed'");
    expect(renderer).toContain("window.__resolveProductionStatus?.(status.sessionId)");
    expect(renderer).toContain('statusFocusPreserved');
    expect(renderer).toContain('closeFocusReturned');
    expect(renderer).toContain('escapeFocusReturned');
    expect(renderer).toContain('resumeFocusTransferred');
    expect(renderer).toContain("resume.setAttribute('aria-label', t('Resume {0}', localizeChatTitle(tab.title)))");
    expect(probe).not.toContain('missingFont.result.assertions.realVisibleColor');
    expect(probe).toContain('recentGeometry: baseline.result.recentGeometry');
  });
});
