package main

import (
	"bytes"
	"errors"
	"testing"
	"testing/quick"
	"time"

	"github.com/makscee/void-code/internal/auth"
)

// The example tests in login_json_test.go each pin one path through the flow.
// This file pins the shape every path must have, no matter which one a given
// run takes: the desktop GUI has no way to tell "still working" from "done"
// other than counting terminal events on the stream, so there must be
// exactly one, and it must agree with the Go error the function returns.
//
// The generator below drives runDeviceLoginJSON through combinations of a
// failing or succeeding start, an arbitrary bounded sequence of poll
// outcomes (continuable and terminal), a failing or succeeding install, and
// a clock that advances by whatever the code under test actually sleeps —
// so the deadline path is reachable, not just the fixed few paths the
// example tests already cover by hand.

// errUnknownPollFailure stands in for a poll failure that isn't one of the
// mapped sentinels in internal/auth/errors.go. deviceLoginJSONReason must
// still produce a stable word for it, not just for the errors it knows.
var errUnknownPollFailure = errors.New("simulated unknown poll failure")

// errSimulatedInstallFailure is returned by the fake install seam so the
// property can exercise "the token wouldn't save" without a real keychain.
var errSimulatedInstallFailure = errors.New("simulated install failure")

// pollOutcome is one entry a generated scenario can pick for a poll call.
// terminal marks the ones that end the loop (success or a terminal error);
// the rest (pending, slow-down) are the ones the loop is supposed to eat
// silently and keep going.
type pollOutcome struct {
	err      error
	terminal bool
}

// outcomeTable is the fixed menu the generator indexes into. It covers every
// branch the poll switch in runDeviceLoginJSON and deviceLoginJSONReason
// distinguish: both continuable errors, every terminal sentinel, an unmapped
// error, and success. Index 0 doubles as the fallback once a scenario's
// explicit outcomes run out (see scenarioServer.deps below).
var outcomeTable = []pollOutcome{
	{auth.ErrAuthPending, false},
	{auth.ErrDeviceSlowDown, false},
	{auth.ErrDeviceExpired, true},
	{auth.ErrDeviceDenied, true},
	{auth.ErrDeviceConsumed, true},
	{auth.ErrDeviceInvalid, true},
	{auth.ErrDeviceRateLimited, true},
	{errUnknownPollFailure, true},
	{nil, true}, // nil marks success: the poll call returns a token, not an error
}

// maxPollOutcomes bounds how many generated bytes a scenario gets to spend on
// poll answers. Past this the fake server falls back to "pending" for every
// further call, same as an exhausted list — an unbounded sequence paired
// with a clock that only moves on sleep is exactly the shape of test that
// hangs, so the bound has to be a hard cap, not a hope.
const maxPollOutcomes = 20

// deviceLoginScenario is what testing/quick generates. Every field is a
// plain stdlib-generatable type (bool, uint8, []uint8) so quick.Value builds
// it without a custom Generator; deps() below turns the raw values into the
// actual seams.
type deviceLoginScenario struct {
	StartFails   bool
	ExpiresIn    uint8
	IntervalSec  uint8
	InstallFails bool
	Outcomes     []uint8
}

// scenarioServer holds the mutable state one generated run produces:
// how many times poll was called, what got installed, and a clock that only
// moves when the code under test sleeps — so ExpiresIn (max 255s) and a
// minimum 1s-per-iteration interval together bound the run to at most a few
// hundred loop iterations, deterministically, with no wall-clock sleeping.
type scenarioServer struct {
	scenario  deviceLoginScenario
	polls     int
	next      int
	installed string
	clock     time.Time
}

func (s *scenarioServer) deps() deviceLoginDeps {
	startResult := auth.DeviceStartResult{
		DeviceCode:       "prop-device-code",
		UserCode:         "PROP1234",
		VerificationPath: "/device",
		ExpiresIn:        int(s.scenario.ExpiresIn),
		Interval:         int(s.scenario.IntervalSec),
	}
	return deviceLoginDeps{
		start: func() (auth.DeviceStartResult, error) {
			if s.scenario.StartFails {
				return auth.DeviceStartResult{}, errors.New("simulated start failure")
			}
			return startResult, nil
		},
		poll: func(string) (auth.DevicePollResult, error) {
			s.polls++
			outcome := outcomeTable[0] // fallback once the scenario's outcomes are spent: keep waiting
			if s.next < len(s.scenario.Outcomes) && s.next < maxPollOutcomes {
				outcome = outcomeTable[int(s.scenario.Outcomes[s.next])%len(outcomeTable)]
				s.next++
			}
			if outcome.err == nil {
				return auth.DevicePollResult{Token: "prop.session.token"}, nil
			}
			return auth.DevicePollResult{}, outcome.err
		},
		install: func(token string) error {
			if s.scenario.InstallFails {
				return errSimulatedInstallFailure
			}
			s.installed = token
			return nil
		},
		sleep: func(d time.Duration) { s.clock = s.clock.Add(d) },
		now:   func() time.Time { return s.clock },
		browserURL: func(path string) string {
			return "https://auth.example.test" + path
		},
	}
}

// run drives one generated scenario and returns the parsed event stream
// alongside the error runDeviceLoginJSON returned, for the properties below
// to check. Parsing reuses the events helper from login_json_test.go —
// same package, no need for a second copy.
func (s *scenarioServer) run(t *testing.T) (evts []map[string]any, err error) {
	t.Helper()
	var out bytes.Buffer
	err = runDeviceLoginJSON(s.deps(), &out)
	return events(t, &out), err
}

// TestDeviceLoginJSONEndsWithExactlyOneTerminalEvent is the property that
// matters most: the desktop GUI has nothing but this stream to decide "still
// waiting" versus "done, here's why". Zero terminal events (today's bug on a
// failed device start — it returns an error and writes nothing) leaves the
// window on its spinner forever; two would tell it two contradictory things.
// Folded into the same check, because they're the same well-formedness
// claim about that one terminal event: the returned Go error must agree
// with which kind of terminal event was written, and an error event must
// always carry a reason a UI can branch on — a bare {"event":"error"} is as
// useless to the reader as no event at all.
func TestDeviceLoginJSONEndsWithExactlyOneTerminalEvent(t *testing.T) {
	property := func(scenario deviceLoginScenario) bool {
		server := &scenarioServer{scenario: scenario, clock: time.Unix(0, 0)}
		events, err := server.run(t)

		terminal, authorizedCount, errorEvents := 0, 0, 0
		var lastErrorReason string
		lastErrorReasonOK := false
		for _, e := range events {
			switch e["event"] {
			case "authorized":
				terminal++
				authorizedCount++
			case "error":
				terminal++
				errorEvents++
				reason, ok := e["reason"].(string)
				lastErrorReason, lastErrorReasonOK = reason, ok
			case "prompt":
				// not terminal
			default:
				t.Logf("scenario %+v: unexpected event kind %v in %v", scenario, e["event"], events)
				return false
			}
		}

		if terminal != 1 {
			t.Logf("scenario %+v: terminal events = %d, want exactly 1; events = %v", scenario, terminal, events)
			return false
		}

		hasError := err != nil
		isErrorEvent := errorEvents == 1
		if hasError != isErrorEvent {
			t.Logf("scenario %+v: err = %v but terminal event kind disagrees; events = %v", scenario, err, events)
			return false
		}

		if isErrorEvent && (!lastErrorReasonOK || lastErrorReason == "") {
			t.Logf("scenario %+v: error event has no non-empty reason; events = %v", scenario, events)
			return false
		}

		return true
	}

	if err := quick.Check(property, &quick.Config{MaxCount: 300}); err != nil {
		t.Fatal(err)
	}
}

// TestDeviceLoginJSONEmitsAtMostOnePrompt guards the other half of the GUI's
// model: it puts the code on screen and opens a browser exactly once per
// prompt event. A second prompt — say, from a retry path that re-ran the
// start call — would flash a new code at a user who already typed the first
// one in.
func TestDeviceLoginJSONEmitsAtMostOnePrompt(t *testing.T) {
	property := func(scenario deviceLoginScenario) bool {
		server := &scenarioServer{scenario: scenario, clock: time.Unix(0, 0)}
		events, _ := server.run(t)

		prompts := 0
		for _, e := range events {
			if e["event"] == "prompt" {
				prompts++
			}
		}
		if prompts > 1 {
			t.Logf("scenario %+v: prompt emitted %d times, want at most 1; events = %v", scenario, prompts, events)
			return false
		}
		return true
	}

	if err := quick.Check(property, &quick.Config{MaxCount: 300}); err != nil {
		t.Fatal(err)
	}
}

// TestDeviceLoginJSONInstallsTokenExactlyOnAuthorization ties the visible
// stream to the side effect the desktop actually cares about: it re-enables
// its chat button on `authorized`, so a token that never landed would leave
// the app talking to a service it isn't authenticated against, and a token
// that landed without the event would leave the button permanently
// disabled.
func TestDeviceLoginJSONInstallsTokenExactlyOnAuthorization(t *testing.T) {
	property := func(scenario deviceLoginScenario) bool {
		server := &scenarioServer{scenario: scenario, clock: time.Unix(0, 0)}
		events, _ := server.run(t)

		authorized := false
		for _, e := range events {
			if e["event"] == "authorized" {
				authorized = true
			}
		}

		installed := server.installed != ""
		if installed != authorized {
			t.Logf("scenario %+v: installed = %q, authorized event present = %v; events = %v", scenario, server.installed, authorized, events)
			return false
		}
		return true
	}

	if err := quick.Check(property, &quick.Config{MaxCount: 300}); err != nil {
		t.Fatal(err)
	}
}
